### ISSUE TITLE
ZIP archives compressed with Keka (and possibly other programs) don't show attachments when uploaded

### ISSUE THREAD

**Issue by Drjacky** [Pustur/whatsapp-chat-parser-website#21] opened 2022-10-23 13:30 UTC
<img width="687" alt="Screen Shot 2022-10-23 at 14 29 30" src="https://user-images.githubusercontent.com/2296754/197395020-a1c79162-7256-4044-8536-3c4ecbbfa0c5.png">
But it's there:
<img width="392" alt="Screen Shot 2022-10-23 at 14 29 44" src="https://user-images.githubusercontent.com/2296754/197395035-863089c0-38f2-46fb-aa69-d73fd55e2b06.png">

**Comment by Pustur** [comment] 2022-10-23 13:34
Would it be possible to send me the zip file privately? So I can see if I can replicate the issue.

You can reach me out at loris.bettazza@gmail.com

**Comment by Drjacky** [comment] 2022-10-23 13:58
I realized if I use the official zip that WhatsApp generated (after exporting the chat), it works (displaying images); But when I compress(zip) the extracted older(from the original zip generated by WA) by [Keka](https://www.keka.io/en/), it doesn't display the images.

So, to simulate the issue, you'd probably need to export a chat, then extract it, then remove that original archive, and then compress the folder into ZIP by Keka.

**Comment by Pustur** [comment] 2022-10-23 14:30
Thanks for the info.

I can confirm that re-compressing the folder with keka does indeed cause problems when reading the attachments. I may look into it but it's very low priority since I assume this is an issue that very few people are going to encounter.

**Comment by Pustur** [comment] 2022-10-28 19:25
Ok I looked into it and basically the original zip export from whatsapp does not contain a folder. I tried again to compress only the files without the folder with keka and it works.

So I'll close this issue as this is not really a bug with the site, but with the structure of the zip file.

**Closed by Pustur** 2022-10-28 19:25 UTC
Labels: bug
